import React from 'react';
import { Bot, Lightbulb, Activity, Stethoscope } from 'lucide-react';

interface LlmAnswerProps {
  answer: string;
}

export const LlmAnswer: React.FC<LlmAnswerProps> = ({ answer }) => {
  
  // A simple way to structure the text if the backend sends markdown headers.
  // In a production app, use 'react-markdown'. Here we do a custom render for specific sections.
  
  const sections = [
    { id: 'findings', title: 'Findings & Observations', icon: <Activity className="w-5 h-5 text-blue-600" />, keywords: ['Findings', 'Observations'] },
    { id: 'alarms', title: 'Alarms & Anomalies', icon: <AlertCardIcon />, keywords: ['Alarms', 'Anomalies', 'Spike'] },
    { id: 'diagnostics', title: 'Diagnostics', icon: <Stethoscope className="w-5 h-5 text-purple-600" />, keywords: ['Diagnostics', 'Cause'] },
    { id: 'recommendations', title: 'Recommendations', icon: <Lightbulb className="w-5 h-5 text-amber-500" />, keywords: ['Recommendations', 'Actions'] },
  ];

  // Very basic markdown stripping for demo purposes
  const cleanText = (text: string) => text.replace(/###/g, '').replace(/\*\*/g, '').trim();

  // Helper to find content between headers (Rough parsing for visual separation)
  const getContentForSection = (keywords: string[]) => {
    const lowerAnswer = answer.toLowerCase();
    const indices = keywords.map(k => lowerAnswer.indexOf(k.toLowerCase())).filter(i => i !== -1);
    if (indices.length === 0) return null;
    
    const startIndex = Math.min(...indices);
    // Find next section start
    let endIndex = answer.length;
    // This is a naive parser logic for the specific demo format
    // Real implementation would use a proper Markdown AST
    const nextSections = ['### Findings', '### Alarms', '### Diagnostics', '### Recommendations']
        .filter(s => !keywords.some(k => s.toLowerCase().includes(k.toLowerCase())));
        
    for (const next of nextSections) {
        const idx = answer.indexOf(next, startIndex + 10); // offset to avoid self
        if (idx !== -1 && idx < endIndex) endIndex = idx;
    }

    let content = answer.substring(startIndex, endIndex);
    // Remove the header line
    content = content.substring(content.indexOf('\n') + 1).trim();
    return content;
  };

  return (
    <div className="bg-white rounded-xl shadow-lg border border-polimi-100 overflow-hidden">
      <div className="bg-gradient-to-r from-polimi-900 to-polimi-700 px-6 py-4 flex items-center gap-3 text-white">
        <Bot className="w-6 h-6" />
        <h2 className="text-lg font-semibold tracking-wide">AI Analysis Report</h2>
      </div>
      
      <div className="p-6 grid gap-6">
        {sections.map((section) => {
            const content = getContentForSection(section.keywords);
            if (!content) return null;

            return (
                <div key={section.id} className="relative pl-4 border-l-4 border-slate-100 hover:border-polimi-200 transition-colors">
                    <div className="flex items-center gap-2 mb-2">
                        {section.icon}
                        <h3 className="font-bold text-slate-800">{section.title}</h3>
                    </div>
                    <div className="text-slate-600 leading-7 text-sm whitespace-pre-line">
                        {/* Highlighting bold parts manually for demo */}
                        {content.split('**').map((part, i) => 
                            i % 2 === 1 ? <span key={i} className="font-bold text-slate-900 bg-slate-100 px-1 rounded">{part}</span> : part
                        )}
                    </div>
                </div>
            )
        })}
        
        {/* Fallback if parsing fails, show raw */}
        {!sections.some(s => getContentForSection(s.keywords)) && (
            <div className="prose prose-sm max-w-none text-slate-700">
                {answer}
            </div>
        )}
      </div>
      
      <div className="bg-slate-50 px-6 py-3 border-t border-slate-100 text-xs text-slate-400 text-right">
        Generated by IoT-LLM Agent (GPT-5 Preview)
      </div>
    </div>
  );
};

const AlertCardIcon = () => (
    <svg className="w-5 h-5 text-red-500" fill="none" viewBox="0 0 24 24" stroke="currentColor">
        <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M12 9v2m0 4h.01m-6.938 4h13.856c1.54 0 2.502-1.667 1.732-3L13.732 4c-.77-1.333-2.694-1.333-3.464 0L3.34 16c-.77 1.333.192 3 1.732 3z" />
    </svg>
)
